### ISSUE TITLE
OCPP charger

### ISSUE THREAD

**Issue by swaminirbhay** [andig/evcc-config#32]
I want to control a charger, that is using OCPP over WLAN/LAN. 
Is there any work already done on this topic?

[DaheimLaden Handbuch V.1 V.2.pdf](https://github.com/andig/evcc-config/files/6364364/DaheimLaden.Handbuch.V.1.V.2.pdf)

**Comment by andig** [comment]
Not currently. Please open request at https://github.com/andig/evcc/issues. Could you provide access to a charger for testing?

**Comment by swaminirbhay** [comment]
Unfortunately I don't yet own one of these chargers, but the company selling them is a start-up and so they might be cooperative.

**Comment by andig** [comment]
Feel free to approach them. We're open to discussions.

**Comment by hackex** [comment]
I also like the idea to include OCPP functionality.

**Comment by andig** [comment]
> I also like the idea to include OCPP functionality.

As written above. This won‘t happen unless I can get a device for testing.

**Comment by hackex** [comment]
> > I also like the idea to include OCPP functionality.
> 
> As written above. This won‘t happen unless I can get a device for testing.

Das würde man schon hinbekommen. Soll die bei dir stehen oder geht auch remote? Muss ein Auto daran angeschlossen sein? Hätte ggf. eine EVbox Elvi zum testen.
Wäre EVCC dann gleichzeitig das Backend? Oder würde EVCC noch an ein Backend angeschlossen werden?

**Comment by andig** [comment]
Remote ginge mindestens zu Beginn. Evcc wäre dann das Backend.

**Comment by swaminirbhay** [comment]
Hallo Andi,

 

ich habe mich nun für eine andere Box entschieden. Go-e wird bereits von OpenWB unterstützt und bietet mittlerweile auch Umschalten zwischen 1- und 3-phasigem Laden an. Im Moment kann man das immerhin schon mit der App steuern, demnächst soll auch die API überarbeitet werden.

 

Insofern kann ich Dich leider nicht beim OCPP Thema unterstützen.

 

Beste Grüße

 

Roger Gehrmann

 

Malterhausen Siedlung 28

14913 Niedergörsdorf

 

Tel. +49-30-555 77 0 44

Mobile +49-151-5010 2784

 

 

Von: hackex ***@***.***> 
Gesendet: Sonntag, 27. Juni 2021 17:48
An: andig/evcc-config ***@***.***>
Cc: swaminirbhay ***@***.***>; Author ***@***.***>
Betreff: Re: [andig/evcc-config] OCPP charger (#32)

 

I also like the idea to include OCPP functionality.

As written above. This won‘t happen unless I can get a device for testing.

Das würde man schon hinbekommen. Soll die bei dir stehen oder geht auch remote? Muss ein Auto daran angeschlossen sein? Hätte ggf. eine EVbox Elvi zum testen.
Wäre EVCC dann gleichzeitig das Backend? Oder würde EVCC noch an ein Backend angeschlossen werden?

**Comment by andig** [comment]
Danke @swaminirbhay. @hackex lass uns die Diskussion bitte hier https://github.com/andig/evcc/issues/1139 im Hauptrepo weiter führen damit andere auch teilnehmen können.
